name: Rebuild Docs
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  rebuildpages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout multiple_pages
      uses: actions/checkout@v2
      with:
        ref: master
    - name: 'Build docs'
      working-directory: assets
      shell: pwsh
      run: |
        curl -O https://raw.githubusercontent.com/sqlcollaborative/dbatools/master/bin/dbatools-index.json
        $OutputFolder = (Get-Location).Path
        Write-Host "running in $OutputFolder"
        Get-ChildItem $OutputFolder 
        ./templates/to_md.ps1
      
    - name: commit if file changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: refreshing docs pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
